# Generated by Django 2.2.3 on 2020-03-25 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'In Process'), (1, 'Controlled')], default=0)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('production_order_no', models.CharField(max_length=200, unique=True)),
                ('order_position_no', models.CharField(max_length=200, unique=True)),
                ('reference_no', models.CharField(max_length=200, unique=True)),
                ('quantity', models.CharField(max_length=200, unique=True)),
                ('working_pressure', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Process_first',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In Process'), (1, 'Controlled')], default=0)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('soru1', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0)),
                ('soru2', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0)),
                ('soru3', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0)),
                ('soru4', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0)),
                ('soru5', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process1', to='processes.Product')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
