# Generated by Django 3.0.8 on 2020-09-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_1',
            name='urun',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
