# Generated by Django 2.2.3 on 2020-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
