# Generated by Django 2.2.3 on 2020-05-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20200504_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_3',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q9',
        ),
        migrations.AddField(
            model_name='process_2',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Ön montaj için ürün dosyasını teslim aldım.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Pompalar doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kampana elektrik motoru ve pompaya uygundur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kaplin takımı elektrik motoru ve pompaya uygundur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Dişli pompa montaj flanşları temin edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Basınç filtresi doğrudur'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Dönüş filtresi doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Dönüş filtresi temizliği için kullanılan 3 yollu küresel vana doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü/aküler doğrudur'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü montaj kelepçe ve plakaları doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q19',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü emniyet bloğu doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Tank teslim alınmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Soğutucu doğrudur. Montaj yeri açısından '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q21',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kompansatör doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q22',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kelebek vana doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q23',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Tank tahliye kürsel vanası doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q24',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Isıtıcı doğrudur. Tankta perde sacı veya diğer bir ekipmana çarpmamaktadır'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q25',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Seviye göstergeleri doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q26',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Seviye şalteri doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q27',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Manometreler doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q28',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Minimes rekoru doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q29',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Minimes hortumu doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Valf standı teslim alınmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q30',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Bağlantı flanşları doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q31',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Paslanmaz fittingsler ve borular doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q32',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Yansanayien temin edilen borular doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q33',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Nem alıcı (silikajel) / hava filtresi doğrudur.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q34',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Klemens kutusu doğrudur. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü standın teslim alınmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Montaj için gerekli diğer sac parçalar doğru ve eksiksizdir. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Depo kapakları doğrudur . '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Ünite blokları teslim alınmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Elektrik motoru doğrudur. Yapı büyüklüğü ve kW cinsinden '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Elektrik motoru titreşim takozları doğrudur.'),
        ),
    ]
