# Generated by Django 2.2.3 on 2020-03-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_product_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cover',
            new_name='picture',
        ),
    ]
