# Generated by Django 3.0.8 on 2020-09-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_process_1_urun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=30), on_delete=django.db.models.deletion.CASCADE, related_name='product_process1', to='processes.Product', verbose_name='Product Name'),
        ),
    ]
