# Generated by Django 2.2.3 on 2020-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20200504_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_2',
            name='q35',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akuplaj eksiksiz monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q36',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akuplajda yağ tavası varsa montajı yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q37',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akuplajın tanka montajı yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q38',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Bloklar test ettirilmiştir. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q39',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Blokların tank geri dönüş boruları monte edilmiş ve tanka montajı tamamlanmıştır. '),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q40',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Basınç filtresi montajı yağ giriş yönü kontrol edilerek yapılmış ve filtre elemanını değiştirmek için yeterli alan vardır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q41',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Dönüş filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q42',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Soğutcu montajı filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q43',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü montajı yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q44',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Hava filtresi / nem alıcı (silikajel) monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q45',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Hortum bağlantıları ve ölçüleri belirlenmiş ve sipariş edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q46',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Manometre sacı kaynatılmış ve manometreler monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q47',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Transmitter, termostat gibi tanka montajı yapılan montaj parçalarının koruma sacları kaynatılmış ve parçalar monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q48',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Klemens kutusu sacı kaynatılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q49',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Valf standı montajı eksiksiz yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q50',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü standı montajı eksiksiz yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q51',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Montaj ve demontaj işlemlerinde zorluk çıkartabilecek borulamalar önceden tespit edilmiş ve tasarım bölümüne bilgi verilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_2',
            name='q52',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Blok bağlantı lamaları kaynakları tamamlanmıştır.'),
        ),
    ]
