# Generated by Django 2.2.3 on 2020-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_process_8'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_3',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Montaj ve demontaj işlemlerinde zorluk çıkartabilecek borulama yoktur.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü hattı borulaması yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü standı borulaması yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Valf standı borulaması yapılmıştır. '),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Yapılan bütün borulamalar devre şemasına göre yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kullanılan boru çapları devre şemasında belirtilen çaplara ve et kalınlıklarına uygundur.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Bütün boru bağlantılarına ( servis ve müşteri bağlantıları) rahatça ulaşılabiliyor.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Pompa ana dağıtım bloğu borulaması yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Pompa basınç filtresi borulaması yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Basınç filtresi ana dağıtım bloğu borulaması yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Dişli pompa tespit plakası nipeli ve tespit plakası nipelinden ana dağıtım bloğuna borulama yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Bloklar arası borulama yapılmıştır. '),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Tank hattı soğutucu - dönüş filtresi borulaması yapılmıştır. '),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Sirkülasyon hattı borulaması pompa/ soğutucu/ dönüş filtresi arasında yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_3',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Tank hattı- küresel vana (bypass sistemi)  ve dönüş filtresi borulaması yapılmıştır. '),
        ),
    ]
