# Generated by Django 3.0.8 on 2020-09-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20200920_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process1', to='processes.Product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='process_1_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process1_2', to='processes.Product', verbose_name='Hangi Ürün?'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process2', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process2_2', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process3', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_3_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process3_2', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process4', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_4_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process4_2', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process5', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_5_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process5_2', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process6', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_6_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process6_2', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process7', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process7_2', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process8', to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process_8_2',
            name='product',
            field=models.ForeignKey(default=models.CharField(blank=True, max_length=50), on_delete=django.db.models.deletion.CASCADE, related_name='product_process8_2', to='processes.Product'),
        ),
    ]
