# Generated by Django 3.0.8 on 2020-09-21 10:49

from django.db import migrations, models
import django.db.models.deletion
import processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_auto_20200920_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_1',
            name='urun',
        ),
        migrations.AlterField(
            model_name='process_1',
            name='product',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='product_process1', to='processes.Product', verbose_name='Product Name'),
        ),
    ]
