# Generated by Django 2.2.3 on 2020-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_auto_20200504_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_4',
            name='content',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='soru1',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='soru2',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='soru3',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='soru4',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='soru5',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='content',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='soru1',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='soru2',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='soru3',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='soru4',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='soru5',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='content',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='soru1',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='soru2',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='soru3',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='soru4',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='soru5',
        ),
        migrations.AddField(
            model_name='process_4',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kaynak işleminden önce yapılması gereken borulama ve kaynak işlemleri hakkında bilgi aldım, kaynaklanacak malzeme türlerini öğrendim ve WPS lerimi kontrol ettim.'),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Montak parçaları (kablo kanalı, filtre konsolu…vb)  kaynaklarında da yukarıdaki kaynak kontrollerini gerçekleştirdim.'),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Paslanmaz kaynak işlemlerinden sonra yüzey temizleme ve pasivasyon işlemlerini gerçekleştirdim. '),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kaldırma kancalarını kaynatmadan önce yüzeydeki astarı temizledim ve sonrasında kaynak işlemini yaptım. '),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Depo kapağından önce örnek bir sacta saplama kaynağı yaparak koparma testi gerçekleştirdim.'),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Bütün kaynak işlemlerinden önce kaynak yapılacak yüzeyleri yağdan, pas ve vb kirden arındırdım. '),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Depo kapağı saplama kaynaklarını yaptım ve kapak montajını yaparak boyutsal doğruluğunu kontrol ettim. '),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Topraklama civatası kaynağını yaptım'),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Boru/dirsek / flanş kaynaklarında kök kaynağını TIG ve dolgu pasoları MAG ile gerçekleştirdim. '),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kök kaynağı işinden sonra kökte sarkma olup olmadığını kontrol ettim. Sarkma varsa taş moturu ile temizledim.'),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kapak pasolarda yanma oluklarının oluşup oluşmadığını kontrol ettim. '),
        ),
        migrations.AddField(
            model_name='process_4',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='MAG kaynaklarında başlangıç ve bitiş hatası kontrollerini gerçekleştirdim.'),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Boya işlemi öncesi Tankı / Akuplajları / Akü - Valf standını ve montaj parçalarını inceledim ve astar yanıklarını paslı, çizik kirli ve çizik/ darbe almış yüzeyleri tespit ettim ve gerekli boya öncesiz hazırlıkları yaptım.'),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Boya işleminden önce gerekli montaj parçalarını maskeledim ve boya işlemini sipariş formundaki isteklere göre gerçekleştirdim.'),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Kaldırma kulaklarını sarı renkle boyadım'),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Tank üzerinde dışarı çıkıntı yapan yüzeyler veya sivri noktalar varsa sarı renkle boyadım.'),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Boya sonrası gerekli kuruma süresini beklettim. '),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Boya sonrası tank içi temizliği gerçekleştirdim. '),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Boya sonrası yapılan maskelemeleri söktüm ve boyanmamış ve rütuş isteyen yüzeyleri tespit edip gerekli boya işlemleri yaptım.'),
        ),
        migrations.AddField(
            model_name='process_5',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Boya Kalınlığı ölçümünü gerçekleştirdim'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Blok montajlarını gerçekleştirdim.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Soğutucu montajı yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Akü montajı yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Manometreler onte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Isıtıcı montajı yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Sipariş edilen hortumların boyları kontrol edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Sipariş edilen hortumların bağlantı rekorları kontrol edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Sipariş edilen hortumların emniyet kabloları konrol edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Sipariş edilen hortumların imalat tarihi kabul edilmiş ve içinde bulunduğumuz yıl dahil olmak üzere son 2 yıl içinde üretilmiş bir hortumdur.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Hortum basınç değerleri sistemin çalışma ve test basıncından daha büyük değerdedir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q19',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Hortumların monte edildiği alanda, hortumun basıncın etkisiyle hareket etmesi sonucu sürtüneceği başka bir montaj parçası yoktur. '),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Soğutucu montajını gerçekleştirdim. '),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Tüm hidrolik bağlantıların (dirsekler, rekorlar ..vb)  montajı uygun torklar ile sıkılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Hava filtresi monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Nem alıcı (silikajel) monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Termostatlar monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Seviye/sıcaklık göstergesi monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Seviye şalteri monte edilmiştir.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Basınç filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Not relevant')], default=0, verbose_name='Dönüş filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
    ]
