# Generated by Django 2.2.3 on 2020-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_auto_20200504_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='soru1',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Hidrolik Güç Ünitesi izlenebilirlik etiketi takılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='soru2',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Montajçılar, kaynakçılar ve testçiler ünite izlenebilirlik kartını işaretlemişlerdir'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='soru3',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Hidrolik Güç Ünitesinde (HGÜ) herhangi bir görsel uygunsuzluk (darbe, kirlilik, pas, boya) yoktur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Ön montaj için ürün dosyasını teslim aldım.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Pompalar doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kampana elektrik motoru ve pompaya uygundur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kaplin takımı elektrik motoru ve pompaya uygundur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Dişli pompa montaj flanşları temin edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Basınç filtresi doğrudur'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Dönüş filtresi doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Dönüş filtresi temizliği için kullanılan 3 yollu küresel vana doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü/aküler doğrudur'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü montaj kelepçe ve plakaları doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q19',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü emniyet bloğu doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Tank teslim alınmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Soğutucu doğrudur. Montaj yeri açısından '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q21',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kompansatör doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q22',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kelebek vana doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q23',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Tank tahliye kürsel vanası doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q24',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Isıtıcı doğrudur. Tankta perde sacı veya diğer bir ekipmana çarpmamaktadır'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q25',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Seviye göstergeleri doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q26',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Seviye şalteri doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q27',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Manometreler doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q28',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Minimes rekoru doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q29',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Minimes hortumu doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Valf standı teslim alınmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q30',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Bağlantı flanşları doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q31',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Paslanmaz fittingsler ve borular doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q32',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Yansanayien temin edilen borular doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q33',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Nem alıcı (silikajel) / hava filtresi doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q34',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Klemens kutusu doğrudur. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q35',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akuplaj eksiksiz monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q36',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akuplajda yağ tavası varsa montajı yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q37',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akuplajın tanka montajı yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q38',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Bloklar test ettirilmiştir. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q39',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Blokların tank geri dönüş boruları monte edilmiş ve tanka montajı tamamlanmıştır. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü standın teslim alınmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q40',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Basınç filtresi montajı yağ giriş yönü kontrol edilerek yapılmış ve filtre elemanını değiştirmek için yeterli alan vardır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q41',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Dönüş filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q42',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Soğutcu montajı filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q43',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü montajı yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q44',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Hava filtresi / nem alıcı (silikajel) monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q45',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Hortum bağlantıları ve ölçüleri belirlenmiş ve sipariş edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q46',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Manometre sacı kaynatılmış ve manometreler monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q47',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Transmitter, termostat gibi tanka montajı yapılan montaj parçalarının koruma sacları kaynatılmış ve parçalar monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q48',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Klemens kutusu sacı kaynatılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q49',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Valf standı montajı eksiksiz yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Montaj için gerekli diğer sac parçalar doğru ve eksiksizdir. '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q50',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü standı montajı eksiksiz yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q51',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Montaj ve demontaj işlemlerinde zorluk çıkartabilecek borulamalar önceden tespit edilmiş ve tasarım bölümüne bilgi verilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q52',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Blok bağlantı lamaları kaynakları tamamlanmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Depo kapakları doğrudur . '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Ünite blokları teslim alınmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Elektrik motoru doğrudur. Yapı büyüklüğü ve kW cinsinden '),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Elektrik motoru titreşim takozları doğrudur.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='soru1',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='soru2',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='soru3',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='soru4',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='soru5',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Montaj ve demontaj işlemlerinde zorluk çıkartabilecek borulama yoktur.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü hattı borulaması yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü standı borulaması yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Valf standı borulaması yapılmıştır. '),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Yapılan bütün borulamalar devre şemasına göre yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kullanılan boru çapları devre şemasında belirtilen çaplara ve et kalınlıklarına uygundur.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Bütün boru bağlantılarına ( servis ve müşteri bağlantıları) rahatça ulaşılabiliyor.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Pompa ana dağıtım bloğu borulaması yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Pompa basınç filtresi borulaması yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Basınç filtresi ana dağıtım bloğu borulaması yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Dişli pompa tespit plakası nipeli ve tespit plakası nipelinden ana dağıtım bloğuna borulama yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Bloklar arası borulama yapılmıştır. '),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Tank hattı soğutucu - dönüş filtresi borulaması yapılmıştır. '),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Sirkülasyon hattı borulaması pompa/ soğutucu/ dönüş filtresi arasında yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Tank hattı- küresel vana (bypass sistemi)  ve dönüş filtresi borulaması yapılmıştır. '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kaynak işleminden önce yapılması gereken borulama ve kaynak işlemleri hakkında bilgi aldım, kaynaklanacak malzeme türlerini öğrendim ve WPS lerimi kontrol ettim.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Montak parçaları (kablo kanalı, filtre konsolu…vb)  kaynaklarında da yukarıdaki kaynak kontrollerini gerçekleştirdim.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Paslanmaz kaynak işlemlerinden sonra yüzey temizleme ve pasivasyon işlemlerini gerçekleştirdim. '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kaldırma kancalarını kaynatmadan önce yüzeydeki astarı temizledim ve sonrasında kaynak işlemini yaptım. '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Depo kapağından önce örnek bir sacta saplama kaynağı yaparak koparma testi gerçekleştirdim.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Bütün kaynak işlemlerinden önce kaynak yapılacak yüzeyleri yağdan, pas ve vb kirden arındırdım. '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Depo kapağı saplama kaynaklarını yaptım ve kapak montajını yaparak boyutsal doğruluğunu kontrol ettim. '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Topraklama civatası kaynağını yaptım'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Boru/dirsek / flanş kaynaklarında kök kaynağını TIG ve dolgu pasoları MAG ile gerçekleştirdim. '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kök kaynağı işinden sonra kökte sarkma olup olmadığını kontrol ettim. Sarkma varsa taş moturu ile temizledim.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kapak pasolarda yanma oluklarının oluşup oluşmadığını kontrol ettim. '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='MAG kaynaklarında başlangıç ve bitiş hatası kontrollerini gerçekleştirdim.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Boya işlemi öncesi Tankı / Akuplajları / Akü - Valf standını ve montaj parçalarını inceledim ve astar yanıklarını paslı, çizik kirli ve çizik/ darbe almış yüzeyleri tespit ettim ve gerekli boya öncesiz hazırlıkları yaptım.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Boya işleminden önce gerekli montaj parçalarını maskeledim ve boya işlemini sipariş formundaki isteklere göre gerçekleştirdim.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Kaldırma kulaklarını sarı renkle boyadım'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Tank üzerinde dışarı çıkıntı yapan yüzeyler veya sivri noktalar varsa sarı renkle boyadım.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Boya sonrası gerekli kuruma süresini beklettim. '),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Boya sonrası tank içi temizliği gerçekleştirdim. '),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Boya sonrası yapılan maskelemeleri söktüm ve boyanmamış ve rütuş isteyen yüzeyleri tespit edip gerekli boya işlemleri yaptım.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Boya Kalınlığı ölçümünü gerçekleştirdim'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Blok montajlarını gerçekleştirdim.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Soğutucu montajı yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Akü montajı yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Manometreler onte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Isıtıcı montajı yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Sipariş edilen hortumların boyları kontrol edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Sipariş edilen hortumların bağlantı rekorları kontrol edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Sipariş edilen hortumların emniyet kabloları konrol edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Sipariş edilen hortumların imalat tarihi kabul edilmiş ve içinde bulunduğumuz yıl dahil olmak üzere son 2 yıl içinde üretilmiş bir hortumdur.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Hortum basınç değerleri sistemin çalışma ve test basıncından daha büyük değerdedir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q19',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Hortumların monte edildiği alanda, hortumun basıncın etkisiyle hareket etmesi sonucu sürtüneceği başka bir montaj parçası yoktur. '),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Soğutucu montajını gerçekleştirdim. '),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Tüm hidrolik bağlantıların (dirsekler, rekorlar ..vb)  montajı uygun torklar ile sıkılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Hava filtresi monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Nem alıcı (silikajel) monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Termostatlar monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Seviye/sıcaklık göstergesi monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Seviye şalteri monte edilmiştir.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Basınç filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0, verbose_name='Dönüş filtresi montajı yağ giriş yönü kontrol edilerek yapılmıştır.'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='soru1',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='soru2',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='soru3',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='soru4',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='soru5',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='soru1',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='soru2',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='soru3',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='soru4',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='soru5',
            field=models.IntegerField(choices=[(0, 'Evet'), (1, 'Hayır'), (2, 'İlgili Değil')], default=0),
        ),
    ]
