# Generated by Django 3.0.8 on 2020-09-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_auto_20200921_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_1',
            name='urun',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_process1', to='processes.Product', verbose_name='Product Name'),
        ),
    ]
