# Generated by Django 3.0.8 on 2020-09-21 12:21

from django.db import migrations, models
import django.db.models.deletion
import processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_auto_20200921_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_process1', to='processes.Product', verbose_name='Product Name'),
        ),
    ]
