# Generated by Django 3.0.8 on 2020-09-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_auto_20200922_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_2_2',
            old_name='q43',
            new_name='q10',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q111',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q222',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q333',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q444',
        ),
        migrations.RemoveField(
            model_name='process_2',
            name='q32',
        ),
        migrations.RemoveField(
            model_name='process_2',
            name='q33',
        ),
        migrations.RemoveField(
            model_name='process_2',
            name='q34',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q35',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q36',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q37',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q38',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q39',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q40',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q41',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q42',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q44',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q45',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q46',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q47',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q48',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q49',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q50',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q51',
        ),
        migrations.RemoveField(
            model_name='process_2_2',
            name='q52',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='process_3',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q0',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q33',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q44',
        ),
        migrations.RemoveField(
            model_name='process_7_2',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='process_7_2',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='process_7_2',
            name='q3',
        ),
        migrations.AddField(
            model_name='process_1',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Packaging'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q19',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'CONDITIONAL ADMISSION'), (2, 'RED')], default=0, verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q21',
            field=models.IntegerField(blank=True, choices=[(0, 'REXROTH'), (1, 'YANSANAYI')], default=0, verbose_name='Rework by '),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q22',
            field=models.IntegerField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, verbose_name='Cont. by'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q23',
            field=models.IntegerField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, verbose_name='Approvied by'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Pump-Electric Motor assemblied.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Hose connections types, size and lenghts defined and ordered.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Manometer panel welded.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Protection covers are welded of oil tank for heater or switches.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='terminal box connection profile welded.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Valve stans assembly done'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Accumulator stand assembly done.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Design department informed about all asssembly problems '),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Manifold connection plates welded.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q19',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name="Hoses's lenght is defined and ordered."),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Oil pan assemblied.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Pump-Electric Motor group assemblied on tank'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Manifolds  tested'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name="Manifolds's drain lines assemblied ."),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='According the flow direction, pressure filter assemblied and there is enough place for changing filter element.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='According to flow direction return filter assemblied.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Accumulator assemblied.'),
        ),
        migrations.AddField(
            model_name='process_2_2',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Air filter / silika gel type air filter assemblied.'),
        ),
        migrations.AddField(
            model_name='process_6',
            name='q21',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='The hose security chains been correctly fitted? Secure chains lock were pressed.'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q19',
            field=models.IntegerField(blank=True, default=0, verbose_name='Thickness For Second Coat'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q20',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pz.No:'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q21',
            field=models.IntegerField(blank=True, default=0, verbose_name='Bar:'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'INCI MAKINA'), (1, 'SECKIN TORNA'), (2, 'MODCON'), (3, 'TEKNIK CIZGI')], default=0, verbose_name='Sub-industry'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Grinding, Paste'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Cleanliness'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q12',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pri. Coa. Thick. (max 80 µ)'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Missing of Operation'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Welding Quality'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Start-Finish Pol. Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Stainless Tank Pass. Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Alü.Tank Drain Hole Crack Chck'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q2',
            field=models.IntegerField(blank=True, default=0, verbose_name='P. O. No'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q3',
            field=models.IntegerField(blank=True, default=0, verbose_name='Production Order No'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q4',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ident No'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q5',
            field=models.IntegerField(blank=True, default=0, verbose_name='Drawing No'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q6',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantitiy'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'ST37'), (1, 'ST52'), (2, 'PASLANMAZ'), (3, 'ALUMINYUM')], default=0, verbose_name='Tank Type'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Axial Dev'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Deformation'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I received the product file for pre assembly.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Pumps are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Bellhousng is sutable for pumps and electric motors.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Couplings are OK for pumps and electric motors.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Pumps flanges are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Pressure filter is OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Return filter is OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Three way valve is for return filters'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Accumulator/Accumulators are OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Accumulator assembly parts are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q19',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name="Accumulator's safety block is OK"),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I received the oil tank.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Cooling type and its assembly is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q21',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Compensator is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q22',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Butterfly valves are OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q23',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Tank drain valve is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q24',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Heater  is OK and there is no problem for tank assembly.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q25',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Level gauge is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q26',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Level gauge with switch is OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q27',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Manometer type and size is  OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q28',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Flange connections are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q29',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Stainless fittings and pipes are OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I received the valve stand.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q30',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Silica gel / air filter is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q31',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Terminal box is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I received the accumulator stand.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='All assembly parts are correct and there is no missingg part'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Tank cover is Ok'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I received the blocks for power unit.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Electrical motor is checked size and power is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Electric motor damping rods are OK'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Are the pipelines in accordance with the assembly list prefix and hydraulic circuit?'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='If there is contact with other parts, the protection against abrasion been provided. '),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='The hose security chains been correctly fitted? Secure chains lock were pressed.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Are the pipe diameters the same as stated in the hydraulic circuit?'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Are all pipe connections (service connections) or customer connections accessible?'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Are all hydraulic connections (screw connection of flanges and fittings) tight.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Are all the pipes cleaned and preserved?'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Is there any evidence of unpermitted flattening? If there is no specific customer request, standard of DC; otherwise max. is 6% according to ko = [(Dmax – Dmin)/D ] x 100 '),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Were changes in direction avoided in piping? It should be preferably used round arches, angle fittings should be avoided.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='They lay down specific requirements for suction and pressure lines and were these observed? (high dynamic range)'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='The hoses fitted professionaly. (e.g. Bend radii not too small. In case of contact with other parts scoring protector used)'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name="I have already taken information about the material were used for piping and oil tank' mataerial. The used WPS is selected the materials of oil tank and pipes material accordingly."),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I cleaned surfaces and applied passivation liquied for stainless materials welding process.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Before spot welding of cleaning covers of oil tank, I made spt welding and check the parameters of Welding.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='All surfaces were cleaned by rust, paint or oil before welding.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I welded the cleaning  covers than checked the position of cleaning cover on tank.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I welded the grounding element to oil tank.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I applied TIG welding process for root pass of pipe. I applied the MAG welding for cover passess for pipe.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I checked root after root pass of pipe welding. If there is '),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I checked undercuts after cover pass.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I checked start and finish point of MAG welds.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I checked the all surfaces for components of assemby parts and oil tank ( from outside and inside). All surfaced cleaned by rust, dirt and oil.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I checked paint type of request in order form and masked the related surfaces of Power Unit. ( including the rubber and plastic parts) '),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='If there is surface where is extended out of HPU and has a risk for safety the related are is painted with different color.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I waited the dryin period and than checked the hardness of paint.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='All preventive masks remved after painting'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='I measured the thickness of paint.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='The all manifolds assemblied on tank'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Accumulator installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Manometers installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Are all hydraulic connections done and  (pipings,screw connection of flanges and fittings) tighted.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Heater installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Hose lenght contralled'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Security ropes contolled of hoses'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='the production date of hoses controlled. ( its allowed the hose produces in last 2 years) '),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Hose pressure values compared with HPU test pressure'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q19',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='The hoses fitted professionaly. (e.g. Bend radii not too small. In case of contact with other parts scoring protector used)'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='The cooler installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='If there is contact with other parts, the protection against abrasion been provided.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Air filter installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Silica gel installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Thermostat installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Temprature/Level gauge installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Level Switch installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Pressure line filter installed in accordance with flow direction.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Related')], default=0, verbose_name='Returnline filter installed in accordance with flow direction.'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q1',
            field=models.IntegerField(blank=True, default=0, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Return Fittings Control'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Function Test'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Detected')], default=0, verbose_name='Oil Leakage'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Missing Component'), (1, 'Not Missing Component/')], default=0, verbose_name='Missing Parts'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Oil reservoir has been checked from inside after test '),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q15',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q16',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ral Code For Prime Coat'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q17',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ral Code For Second Coat'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q18',
            field=models.IntegerField(blank=True, default=0, verbose_name='Thickness For Prime Coat'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sys. Pressur'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q22',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q3',
            field=models.IntegerField(blank=True, default=0, verbose_name='Test Press'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q4',
            field=models.IntegerField(blank=True, default=0, verbose_name='Hyd.Circuit No'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Hyd.Circuit No'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Assemb. Control'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Elec.Mot.Return Dir. '),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Hose Control'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Fittings Control'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Cleanliness,Oil,Paint Failure'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Lifting Eyes'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Traceability Labe'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Marker of Prod. Employee'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Other Ass. Part Package'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Deformation, Rust'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Open holes closed'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Missing Component'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Hose Press Lim/ Security Rope'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='WARNING Labels'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Press. Filter Flow Direction'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Oil Leakage'),
        ),
    ]
