# Generated by Django 3.0.8 on 2020-09-23 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0016_remove_product_ident_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 9, 23), verbose_name='Order Date '),
        ),
    ]
