# Generated by Django 3.0.8 on 2020-09-23 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0017_auto_20200923_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name='Order Date '),
        ),
    ]
