# Generated by Django 3.0.8 on 2020-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0018_auto_20200923_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_1',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q21',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q22',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q23',
        ),
        migrations.AddField(
            model_name='process_1_2',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'CONDITIONAL ADMISSION'), (2, 'RED')], default=0, verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='process_1_2',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Rexroth'), (1, 'Supplier')], default=0, verbose_name='Rework by '),
        ),
        migrations.AddField(
            model_name='process_1_2',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, verbose_name='Cont. by'),
        ),
        migrations.AddField(
            model_name='process_1_2',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, verbose_name='Approvied by'),
        ),
        migrations.AlterField(
            model_name='process_8_2',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Rexroth'), (1, 'Supplier')], default=0, verbose_name='Ek İşlem'),
        ),
    ]
