# Generated by Django 3.0.8 on 2020-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0019_auto_20200923_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ident No'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Drawing No'),
        ),
    ]
