# Generated by Django 3.0.8 on 2020-09-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0021_auto_20200923_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_2_2',
            name='q10',
        ),
    ]
