# Generated by Django 3.0.8 on 2020-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0022_remove_process_2_2_q10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_6',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Are all hydraulic connections done and  (pipings,screw connection of flanges and fittings) tighted.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Heater installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Hose lenght contralled'),
        ),
    ]
