# Generated by Django 3.0.8 on 2020-09-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0023_auto_20200923_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_7',
            name='q5',
        ),
    ]
