# Generated by Django 3.0.8 on 2020-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0026_auto_20200924_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'ST37'), (1, 'ST52'), (2, 'PASLANMAZ'), (3, 'ALUMINYUM')], default=0, verbose_name='Tank Material'),
        ),
    ]
