# Generated by Django 3.0.8 on 2020-09-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0030_auto_20200924_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'INCI MAKINA'), (1, 'SECKIN TORNA'), (2, 'MODCON'), (3, 'TEKNIK CIZGI')], default=0, verbose_name='Supplier'),
        ),
    ]
