# Generated by Django 3.0.8 on 2020-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0031_auto_20200924_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_7',
            name='q21',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q22',
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, verbose_name='Tested By'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, verbose_name='Controlled By'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q20',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
