# Generated by Django 3.0.8 on 2020-09-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0032_auto_20200925_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_8_2',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='process_8_2',
            name='q6',
        ),
    ]
