# Generated by Django 3.0.8 on 2020-09-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0033_auto_20200928_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_1',
            name='q20',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 1 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q21',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 2 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q22',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 3 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q23',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 4 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q24',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 5 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q25',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 6 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q26',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 7 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q27',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 8 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q28',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 9 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q29',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimension 10 : Drw. Mea - Sample 1 - Sample 2 Fill in the form (... - ... - ...)'),
        ),
    ]
