# Generated by Django 3.0.8 on 2020-09-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0035_auto_20200929_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_7',
            name='q21',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 1 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q22',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 2 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q23',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 3 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q24',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 4 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q25',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 5 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q26',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 6 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q27',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 7 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q28',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 8 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q29',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 9 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q30',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 10 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q31',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 11 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q32',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 12 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q33',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 13 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q34',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 14 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q35',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 15 : Pz. No - Bar Fill in the form (... ...)'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q36',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 16 : Pz. No - Bar Fill in the form (... ...)'),
        ),
    ]
