# Generated by Django 3.0.8 on 2020-09-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0036_auto_20200929_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_7',
            name='q7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Elec.Mot.Return Dir. (Ex: 1 2 3 4 ...)'),
        ),
    ]
