# Generated by Django 3.0.8 on 2020-09-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0037_auto_20200929_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q19',
            field=models.CharField(blank=True, max_length=600, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q15',
            field=models.CharField(blank=True, max_length=600, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q20',
            field=models.CharField(blank=True, max_length=600, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='content',
            field=models.CharField(blank=True, max_length=600, verbose_name='Remarks'),
        ),
    ]
