# Generated by Django 3.0.8 on 2020-09-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0038_auto_20200929_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q19',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
