# Generated by Django 3.0.8 on 2020-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0039_auto_20200929_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_7',
            name='q15',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q20',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='content',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
