# Generated by Django 3.0.8 on 2020-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0040_auto_20200929_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_8',
            name='q16',
        ),
        migrations.AddField(
            model_name='product',
            name='customer_order_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Customer Order No'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageno',
            field=models.IntegerField(blank=True, default=0, verbose_name='Drawing No:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_order_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Production Order No'),
        ),
    ]
