# Generated by Django 3.0.8 on 2020-09-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0041_auto_20200929_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_1',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='process_1',
            name='q6',
        ),
    ]
