# Generated by Django 3.0.8 on 2020-09-30 08:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0042_auto_20200929_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_7',
            name='q7',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], max_length=32, verbose_name='Elec.Mot.Return Dir.'),
        ),
    ]
