# Generated by Django 3.0.8 on 2020-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0043_auto_20200930_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_7',
            name='q37',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 1 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q38',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 2 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q39',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 3 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q40',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 4 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q41',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 5 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q42',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 6 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q43',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 7 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q44',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 8 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q45',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 9 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q46',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 10 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q47',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 11 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q48',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 12 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q49',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 13 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q50',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 14 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q51',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 15 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q52',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 16 : Bar'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q21',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 1 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q22',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 2 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q23',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 3 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q24',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 4 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q25',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 5 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q26',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 6 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q27',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 7 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q28',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 8 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q29',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 9 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q30',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 10 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q31',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 11 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q32',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 12 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q33',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 13 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q34',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 14 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q35',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 15 : Pz'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q36',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 16 : Pz'),
        ),
    ]
