# Generated by Django 3.0.8 on 2020-09-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0044_auto_20200930_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_7',
            name='q16',
            field=models.IntegerField(blank=True, default=0, verbose_name='Paint requirements'),
        ),
    ]
