# Generated by Django 3.0.8 on 2020-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0048_auto_20200930_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_1',
            name='q30',
            field=models.CharField(blank=True, max_length=200, verbose_name='4N1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q31',
            field=models.CharField(blank=True, max_length=200, verbose_name='4N2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q32',
            field=models.CharField(blank=True, max_length=200, verbose_name='5R1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q33',
            field=models.CharField(blank=True, max_length=200, verbose_name='5N1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q34',
            field=models.CharField(blank=True, max_length=200, verbose_name='5N2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q35',
            field=models.CharField(blank=True, max_length=200, verbose_name='6R'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q36',
            field=models.CharField(blank=True, max_length=200, verbose_name='6N1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q37',
            field=models.CharField(blank=True, max_length=200, verbose_name='6N2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q38',
            field=models.CharField(blank=True, max_length=200, verbose_name='7R'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q39',
            field=models.CharField(blank=True, max_length=200, verbose_name='7N1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q40',
            field=models.CharField(blank=True, max_length=200, verbose_name='7N2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q41',
            field=models.CharField(blank=True, max_length=200, verbose_name='8R1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q42',
            field=models.CharField(blank=True, max_length=200, verbose_name='8N1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q43',
            field=models.CharField(blank=True, max_length=200, verbose_name='8N2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q44',
            field=models.CharField(blank=True, max_length=200, verbose_name='9R1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q45',
            field=models.CharField(blank=True, max_length=200, verbose_name='9N1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q46',
            field=models.CharField(blank=True, max_length=200, verbose_name='9N2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q47',
            field=models.CharField(blank=True, max_length=200, verbose_name='10R1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q48',
            field=models.CharField(blank=True, max_length=200, verbose_name='10N1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q49',
            field=models.CharField(blank=True, max_length=200, verbose_name='10N2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q20',
            field=models.CharField(blank=True, max_length=200, verbose_name='1R1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q21',
            field=models.CharField(blank=True, max_length=200, verbose_name='1N1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q22',
            field=models.CharField(blank=True, max_length=200, verbose_name='1N2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q23',
            field=models.CharField(blank=True, max_length=200, verbose_name='2R1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q24',
            field=models.CharField(blank=True, max_length=200, verbose_name='2N1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q25',
            field=models.CharField(blank=True, max_length=200, verbose_name='2N2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q26',
            field=models.CharField(blank=True, max_length=200, verbose_name='3R1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q27',
            field=models.CharField(blank=True, max_length=200, verbose_name='3N1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q28',
            field=models.CharField(blank=True, max_length=200, verbose_name='3N2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q29',
            field=models.CharField(blank=True, max_length=200, verbose_name='4R1'),
        ),
    ]
