# Generated by Django 3.0.8 on 2020-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0049_auto_20200930_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='assemblied_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tested_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='imageno',
            field=models.CharField(max_length=200, verbose_name='Drawing No:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference_no',
            field=models.CharField(max_length=200, verbose_name='Reference No'),
        ),
        migrations.AlterField(
            model_name='product',
            name='working_pressure',
            field=models.CharField(max_length=200, verbose_name='Working Pressure'),
        ),
    ]
