# Generated by Django 3.0.8 on 2020-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0050_auto_20201001_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference_no',
            field=models.CharField(default='R', max_length=200, verbose_name='Reference No'),
        ),
    ]
