# Generated by Django 3.0.8 on 2020-10-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0051_auto_20201001_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_7',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q4',
        ),
        migrations.AddField(
            model_name='product',
            name='circuitno',
            field=models.IntegerField(blank=True, default=0, verbose_name='Hyd.Circuit No'),
        ),
        migrations.AddField(
            model_name='product',
            name='tank_reference_no',
            field=models.CharField(default=1, max_length=200, verbose_name='Tank Reference No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='imageno',
            field=models.CharField(default='2020/', max_length=200, verbose_name='Drawing No:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='working_pressure',
            field=models.CharField(default='/bar', max_length=200, verbose_name='Working Pressure'),
        ),
    ]
