# Generated by Django 3.0.8 on 2020-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0052_auto_20201001_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_7',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q3',
        ),
        migrations.AddField(
            model_name='product',
            name='press',
            field=models.IntegerField(blank=True, default=0, verbose_name='Test Press'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='Volume'),
        ),
    ]
