# Generated by Django 3.0.8 on 2020-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0053_auto_20201001_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tank_reference_no',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tank Reference No'),
        ),
    ]
