# Generated by Django 3.0.8 on 2020-10-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0055_auto_20201001_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process_1',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 1 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_1_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 1 End List'},
        ),
        migrations.AlterModelOptions(
            name='process_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 2 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_2_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 2 End List'},
        ),
        migrations.AlterModelOptions(
            name='process_3',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 3 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_3_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 3 End List'},
        ),
        migrations.AlterModelOptions(
            name='process_4',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 4 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_4_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 4 End List'},
        ),
        migrations.AlterModelOptions(
            name='process_5',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 5 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_5_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 5 End List'},
        ),
        migrations.AlterModelOptions(
            name='process_6',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 6 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_6_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 6 End List'},
        ),
        migrations.AlterModelOptions(
            name='process_7',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 7 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_7_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 7 End List'},
        ),
        migrations.AlterModelOptions(
            name='process_8',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 8 Start List'},
        ),
        migrations.AlterModelOptions(
            name='process_8_2',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Process 8 End List'},
        ),
    ]
