# Generated by Django 3.0.8 on 2020-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0056_auto_20201001_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='working_pressure',
            field=models.CharField(max_length=200, verbose_name='Working Pressure (bar)'),
        ),
    ]
