# Generated by Django 3.0.8 on 2020-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0059_auto_20201014_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_pressure',
            field=models.IntegerField(blank=True, default=0, verbose_name='System Test Pressure (Bar):'),
        ),
        migrations.AddField(
            model_name='product',
            name='valve_stand_drawing_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Valve Stand Drawing No:'),
        ),
        migrations.AddField(
            model_name='product',
            name='valve_stand_ref_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Valve Stand No:'),
        ),
        migrations.AddField(
            model_name='product',
            name='working_pressure',
            field=models.IntegerField(blank=True, default=0, verbose_name='System Working Pressure (Bar):'),
        ),
    ]
