# Generated by Django 3.0.8 on 2020-10-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0060_auto_20201014_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_1',
            name='q100',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q101',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q102',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q103',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q104',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q105',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q106',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q107',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q108',
            field=models.CharField(blank=True, max_length=200, verbose_name='9M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q109',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q110',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q111',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q112',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q113',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q114',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q115',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q116',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q117',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q118',
            field=models.CharField(blank=True, max_length=200, verbose_name='9P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q119',
            field=models.CharField(blank=True, max_length=200, verbose_name='10M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q120',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q121',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q122',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q123',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q124',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q125',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q126',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q127',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q128',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q129',
            field=models.CharField(blank=True, max_length=200, verbose_name='10P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q130',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q131',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q132',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q133',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q134',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q135',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q136',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q137',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q138',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q139',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q141',
            field=models.CharField(blank=True, max_length=200, verbose_name='12M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q142',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q143',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q144',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q145',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q146',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q147',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q148',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q149',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q150',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q151',
            field=models.CharField(blank=True, max_length=200, verbose_name='12P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q152',
            field=models.CharField(blank=True, max_length=200, verbose_name='13M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q153',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q154',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q155',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q156',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q157',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q158',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q159',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q160',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q161',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q162',
            field=models.CharField(blank=True, max_length=200, verbose_name='13P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q163',
            field=models.CharField(blank=True, max_length=200, verbose_name='14M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q164',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q165',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q166',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q167',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q168',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q169',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q170',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q171',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q172',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q173',
            field=models.CharField(blank=True, max_length=200, verbose_name='14P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q174',
            field=models.CharField(blank=True, max_length=200, verbose_name='15M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q175',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q176',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q177',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q178',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q179',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q180',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q181',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q182',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q183',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q184',
            field=models.CharField(blank=True, max_length=200, verbose_name='15P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q185',
            field=models.CharField(blank=True, max_length=200, verbose_name='16M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q186',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q187',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q188',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q189',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q190',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q191',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q192',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q193',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q194',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q195',
            field=models.CharField(blank=True, max_length=200, verbose_name='16P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q196',
            field=models.CharField(blank=True, max_length=200, verbose_name='17M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q197',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q198',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q199',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q200',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q201',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q202',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q203',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q204',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q205',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q206',
            field=models.CharField(blank=True, max_length=200, verbose_name='17P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q207',
            field=models.CharField(blank=True, max_length=200, verbose_name='18M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q208',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q209',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q210',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q211',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q212',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q213',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q214',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q215',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q216',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q217',
            field=models.CharField(blank=True, max_length=200, verbose_name='18P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q218',
            field=models.CharField(blank=True, max_length=200, verbose_name='19M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q219',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q220',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q221',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q222',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q223',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q224',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q225',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q226',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q227',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q228',
            field=models.CharField(blank=True, max_length=200, verbose_name='19P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q229',
            field=models.CharField(blank=True, max_length=200, verbose_name='20M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q230',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q231',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q232',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q233',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q234',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q235',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q236',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q237',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q238',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q239',
            field=models.CharField(blank=True, max_length=200, verbose_name='20P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q50',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q51',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q52',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q53',
            field=models.CharField(blank=True, max_length=200, verbose_name='4M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q54',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q55',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q56',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q57',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q58',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q59',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q60',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q61',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q62',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q63',
            field=models.CharField(blank=True, max_length=200, verbose_name='4P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q64',
            field=models.CharField(blank=True, max_length=200, verbose_name='5M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q65',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q66',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q67',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q68',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q69',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q70',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q71',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q72',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q73',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q74',
            field=models.CharField(blank=True, max_length=200, verbose_name='5P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q75',
            field=models.CharField(blank=True, max_length=200, verbose_name='6M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q76',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q77',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q78',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q79',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q80',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q81',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q82',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q83',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q84',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q85',
            field=models.CharField(blank=True, max_length=200, verbose_name='6P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q86',
            field=models.CharField(blank=True, max_length=200, verbose_name='7M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q87',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q88',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P2'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q89',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P3'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q90',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P4'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q91',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P5'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q92',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P6'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q93',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P7'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q94',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P8'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q95',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P9'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q96',
            field=models.CharField(blank=True, max_length=200, verbose_name='7P10'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q97',
            field=models.CharField(blank=True, max_length=200, verbose_name='8M'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q98',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P1'),
        ),
        migrations.AddField(
            model_name='process_1',
            name='q99',
            field=models.CharField(blank=True, max_length=200, verbose_name='8P2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Grinding Scratches and Paste Used'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q12',
            field=models.IntegerField(blank=True, default=0, verbose_name='Primary Coating Thickness (max 80 µ)'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='MAG Welding Start Finish Point Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Stainless Tank Passivation Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Aluminium Tank Drain Hole Crack Chck'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q20',
            field=models.CharField(blank=True, max_length=200, verbose_name='1M'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q21',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q22',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q23',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P3'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q24',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P4'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q25',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P5'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q26',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P6'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q27',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P7'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q28',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P8'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q29',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P9'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q30',
            field=models.CharField(blank=True, max_length=200, verbose_name='1P10'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q31',
            field=models.CharField(blank=True, max_length=200, verbose_name='2M'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q32',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q33',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q34',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P3'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q35',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P4'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q36',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P5'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q37',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P6'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q38',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P7'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q39',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P8'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q40',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P9'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q41',
            field=models.CharField(blank=True, max_length=200, verbose_name='2P10'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q42',
            field=models.CharField(blank=True, max_length=200, verbose_name='3M'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q43',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P1'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q44',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P2'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q45',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P3'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q46',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P4'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q47',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P5'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q48',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P6'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q49',
            field=models.CharField(blank=True, max_length=200, verbose_name='3P7'),
        ),
    ]
