# Generated by Django 3.0.8 on 2020-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0061_auto_20201014_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_1',
            name='q140',
            field=models.CharField(blank=True, max_length=200, verbose_name='11P10'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q130',
            field=models.CharField(blank=True, max_length=200, verbose_name='11M'),
        ),
    ]
