# Generated by Django 3.0.8 on 2020-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0062_auto_20201014_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(0, 'INCI MAKINA'), (1, 'SECKIN TORNA'), (2, 'MODCON'), (3, 'TEKNIK CIZGI')], default=3, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Grinding Scratches and Paste Used'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Cleanliness'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Missing of Operation'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Welding Quality'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='MAG Welding Start Finish Point Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Stainless Tank Passivation Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q17',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Aluminium Tank Drain Hole Crack Chck'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q18',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Packaging'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'ST37'), (1, 'ST52'), (2, 'PASLANMAZ'), (3, 'ALUMINYUM')], default=3, verbose_name='Tank Material'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Axial Deviation'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=3, verbose_name='Deformation'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q1',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Cleanliness,Oil,Paint Failure'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q10',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Documentation'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Lifting Eyes'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q12',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Traceability Labe'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q13',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Marker of Prod. Employee'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q14',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Other Ass. Part Package'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Deformation, Rust'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q3',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Open holes closed'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q4',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Missing Component'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Hose Press Lim/ Security Rope'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q6',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Paint Thickness'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='WARNING Labels'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Press. Filter Flow Direction'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(3, '------'), (0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], default=0, verbose_name='Oil Leakage'),
        ),
    ]
