# Generated by Django 3.0.8 on 2020-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0064_auto_20201014_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q8',
            field=models.IntegerField(blank=True, choices=[(4, '------'), (0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], default=4, verbose_name='Axial Deviation'),
        ),
    ]
