# Generated by Django 3.0.8 on 2020-10-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0066_auto_20201014_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q1',
            field=models.IntegerField(choices=[(0, 'INCI MAKINA'), (1, 'SECKIN TORNA'), (2, 'MODCON'), (3, 'TEKNIK CIZGI')], verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q10',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Grinding Scratches and Paste Used'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q11',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Cleanliness'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q12',
            field=models.IntegerField(default=0, verbose_name='Primary Coating Thickness (max 80 µ)'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q13',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Missing of Operation'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q14',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Welding Quality'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q15',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='MAG Welding Start Finish Point Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q16',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Stainless Tank Passivation Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q17',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Aluminium Tank Drain Hole Crack Chck'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q18',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Packaging'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q7',
            field=models.IntegerField(choices=[(0, 'ST37'), (1, 'ST52'), (2, 'PASLANMAZ'), (3, 'ALUMINYUM')], verbose_name='Tank Material'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q8',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Axial Deviation'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q9',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Deformation'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Bellhousng is suitable for pumps and electric motors.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q16',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Three way valve is OK for return filters'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q20',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Cooling size is OK for assembly'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q5',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='All assembly parts are correct and there is no missing part'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q15',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Valve stand assembly done'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q19',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
