# Generated by Django 3.0.8 on 2020-10-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0067_auto_20201014_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q12',
            field=models.IntegerField(default=0, verbose_name='Primary Coating Thickness (µ)'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q9',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Deformation on Surface'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q11',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name="The hose security chains been correctly fitted? Security chain lock's ring pressed."),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q9',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='The hoses fitted professionaly. (e.g. Bend radius not too small. In case of contact with other parts scoring protector used)'),
        ),
    ]
