# Generated by Django 3.0.8 on 2020-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0069_auto_20201014_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_2_2',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Pump-Electric Motor assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q11',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Hose connections types, size and lenghts defined and ordered.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q12',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Manometer panel welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Protection covers are welded of oil tank for heater or switches.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q14',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='terminal box connection profile welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q15',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Valve stand assembly done'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q16',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Accumulator stand assembly done.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q17',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Design department informed about all asssembly problems '),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q18',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Manifold connection plates welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Oil pan assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Pump-Electric Motor group assemblied on tank'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Manifolds  tested'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name="Manifolds's drain lines assemblied ."),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='According the flow direction, pressure filter assemblied and there is enough place for changing filter element.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='According to flow direction return filter assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Accumulator assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Air filter / silika gel type air filter assemblied.'),
        ),
    ]
