# Generated by Django 3.0.8 on 2020-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0070_auto_20201014_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_3',
            name='q12',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
