# Generated by Django 3.0.8 on 2020-10-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0073_auto_20201014_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_4',
            name='q2',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Before spot welding of cleaning covers of oil tank, I made spot welding and check the parameters of Welding.'),
        ),
        migrations.AlterField(
            model_name='process_4',
            name='q7',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I checked root after root pass of pipe welding. If there is sagging, I cleaned it with stone engine.'),
        ),
    ]
