# Generated by Django 3.0.8 on 2020-10-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0076_auto_20201015_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_5',
            name='q0',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ral Code:'),
        ),
    ]
