# Generated by Django 3.0.8 on 2020-10-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0077_process_5_q0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1_2',
            name='q1',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'CONDITIONAL ADMISSION'), (2, 'RED')], verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='process_1_2',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Rexroth'), (1, 'Supplier')], verbose_name='Rework by '),
        ),
        migrations.AlterField(
            model_name='process_1_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], verbose_name='Cont. by'),
        ),
        migrations.AlterField(
            model_name='process_1_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], verbose_name='Approvied by'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q0',
            field=models.IntegerField(verbose_name='Ral Code:'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='I checked the all surfaces for components of assemby parts and oil tank ( from outside and inside). All surfaced cleaned by rust, dirt and oil.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='I checked paint type of request in order form and masked the related surfaces of Power Unit. ( including the rubber and plastic parts) '),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='If there is surface where is extended out of HPU and has a risk for safety the related are is painted with different color.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='I waited the dryin period and than checked the hardness of paint.'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='All preventive masks remved after painting'),
        ),
        migrations.AlterField(
            model_name='process_5',
            name='q6',
            field=models.IntegerField(default=234, verbose_name='I measured the thickness of paint.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='The all manifolds assemblied on tank'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q10',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Accumulator installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q11',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Manometers installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q12',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Are all hydraulic connections done and  (pipings,screw connection of flanges and fittings) tighted.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Heater installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q14',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Hose lenght contralled'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q15',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Hose connection fittings types controlled'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q16',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Security ropes contolled of hoses'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q17',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='the production date of hoses controlled. ( its allowed the hose produces in last 2 years) '),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q18',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Hose pressure values compared with HPU test pressure'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q19',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='The hoses fitted professionaly. (e.g. Bend radii not too small. In case of contact with other parts scoring protector used)'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='The cooler installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q20',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='If there is contact with other parts, the protection against abrasion been provided.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q21',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='The hose security chains been correctly fitted? Secure chains lock were pressed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Air filter installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Silica gel installed.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Thermostat installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q6',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Temprature/Level gauge installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Level Switch installed'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Pressure line filter installed in accordance with flow direction.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Returnline filter installed in accordance with flow direction.'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q10',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Return Fittings Control'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q11',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Function Test'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q12',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Dedected')], verbose_name='Oil Leakage'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], verbose_name='Missing Parts'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q14',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Oil reservoir has been checked from inside after test '),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q16',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ral Code For First Coat'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q6',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Assemb. Control'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q8',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Hose Control'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q9',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Fittings Control'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q1',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Cleanliness,Oil,Paint Failure'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q10',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Documentation'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q11',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Lifting Eyes'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q12',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Traceability Labe'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q13',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Marker of Prod. Employee'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q14',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Other Ass. Part Package'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q2',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Deformation, Rust'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q3',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Open holes closed'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q4',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Missing Component'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q5',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Hose Press Lim/ Security Rope'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q6',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Paint Thickness'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q7',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='WARNING Labels'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q8',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Press. Filter Flow Direction'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q9',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'RED'), (2, 'OUT OF SCOPE')], verbose_name='Oil Leakage'),
        ),
    ]
