# Generated by Django 3.0.8 on 2020-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0078_auto_20201015_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_1_2',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='process_1_2',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='process_1_2',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='process_1_2',
            name='q4',
        ),
        migrations.AddField(
            model_name='process_1',
            name='q1111',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'CONDITIONAL ADMISSION'), (2, 'RED')], default=1, verbose_name='Decision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process_1',
            name='q2222',
            field=models.IntegerField(choices=[(0, 'Rexroth'), (1, 'Supplier')], default=1, verbose_name='Rework by '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process_1',
            name='q3333',
            field=models.IntegerField(choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=1, verbose_name='Cont. by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process_1',
            name='q4444',
            field=models.IntegerField(choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=1, verbose_name='Approvied by'),
            preserve_default=False,
        ),
    ]
