# Generated by Django 3.0.8 on 2020-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0081_process_1_q0'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_2',
            name='q32',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q0',
            field=models.IntegerField(blank=True, default=0, verbose_name='P.O. No:'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q1111',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'CONDITIONAL ADMISSION'), (2, 'RED')], verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q2222',
            field=models.IntegerField(choices=[(0, 'Rexroth'), (1, 'Not Tested')], verbose_name='Rework'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q3333',
            field=models.IntegerField(choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], verbose_name='Controller'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q4444',
            field=models.IntegerField(choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], verbose_name='Approving Person'),
        ),
    ]
