# Generated by Django 3.0.8 on 2020-10-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0082_auto_20201017_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_2_2',
            name='q19',
        ),
    ]
