# Generated by Django 3.0.8 on 2020-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0084_auto_20201218_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_1',
            name='q10',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Grinding Scratches and Paste Used'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q11',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Cleanliness'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q1111',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'CONCESSION'), (2, 'RED')], verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q13',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Missing of Operation'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q14',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Welding Quality'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q15',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='MAG Welding Start Finish Point Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q16',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Stainless Tank Passivation Check'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q17',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Aluminium Tank Drain Hole Crack Chck'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q18',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Packaging'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q3333',
            field=models.CharField(max_length=200, verbose_name='Cont. by'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q4444',
            field=models.CharField(max_length=200, verbose_name='Approvied by'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q7',
            field=models.IntegerField(choices=[(0, 'ST37/ S235'), (1, 'ST52/ S355'), (2, 'Stainless Steel'), (3, 'Aluminium')], verbose_name='Tank Material'),
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q9',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Deformation on Surface'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q1',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Cleanliness,Oil,Paint Failure'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q10',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Documentation'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q11',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Lifting Eyes'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q1111',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'CONCESSION'), (2, 'RED')], verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q12',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Traceability Labe'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q13',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Marker of Prod. Employee'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q14',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Other Ass. Part Package'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q2',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Deformation, Rust'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q3',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Open holes closed'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q4',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Missing Component'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q5',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Hose Press Lim/ Security Rope'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q6',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Paint Thickness'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q7',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='WARNING Labels'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q8',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Press. Filter Flow Direction'),
        ),
        migrations.AlterField(
            model_name='process_8',
            name='q9',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Oil Leakage'),
        ),
    ]
