# Generated by Django 3.0.8 on 2020-12-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0085_auto_20201218_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_1',
            name='q4444',
        ),
        migrations.AddField(
            model_name='process_1_2',
            name='q4444',
            field=models.CharField(default=0, max_length=200, verbose_name='Approvied by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process_1',
            name='q2222',
            field=models.IntegerField(choices=[(2, '.......'), (0, 'Rexroth'), (1, 'Supplier')], verbose_name='Rework by '),
        ),
    ]
