# Generated by Django 3.0.8 on 2020-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0086_auto_20201218_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_2',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='1.I received the product file for pre assembly.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q10',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='10.Pumps are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q11',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='11.Bellhousng is suitable for pumps and electric motors.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q12',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='12.Couplings are OK for pumps and electric motors.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='13.Pumps flanges are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q14',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='14.Pressure filter is OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q15',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='15.Return filter is OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q16',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='16.Three way valve is OK for return line'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q17',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='17.Accumulator/Accumulators are OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q18',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='18.Accumulator assembly parts are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q19',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name="19.Accumulator's safety block is OK"),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='2.I received the oil tank.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q20',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='20.Cooling size is OK for assembly'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q21',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='21.Compensator is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q22',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='22.Butterfly valves are OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q23',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='23.Tank drain valve is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q24',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='24.Heater  is OK and there is no problem for tank assembly.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q25',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='25.Level gauge is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q26',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='26.Level gauge with switch is OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q27',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='27.Manometer type and size is  OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q28',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='28.Flange connections are OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q29',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='29.Stainless fittings and pipes are OK.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='3.I received the valve stand.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q30',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='31.30Silica gel / air filter is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q31',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='32.Terminal box is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='4.I received the accumulator stand.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='5.All assembly parts are correct and there is no missing part'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='6.Tank cover is Ok'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='7.I received the blocks for power unit.'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='8.Electrical motor is checked size and power is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='9.Electric motor damping rods are OK'),
        ),
    ]
