# Generated by Django 3.0.8 on 2020-12-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0087_auto_20201218_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='8.Electric motor is checked , size ,frequency and power is OK.'),
        ),
    ]
