# Generated by Django 3.0.8 on 2020-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0090_auto_20201218_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_2_2',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='33.Pump-Electric Motor assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q11',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='42.Hose connections types, size and lenghts defined and ordered.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q12',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='43.Manometer panel welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='44.Protection covers are welded of oil tank for heater or switches.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q14',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='45.terminal box connection profile welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q15',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='46.Valve stand assembly done'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q16',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='47.Accumulator stand assembly done.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q17',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='48.Design department informed about all asssembly problems '),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q18',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='49.Manifold connection plates welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='34.Oil pan assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='35.Pump-Electric Motor group assemblied on tank'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='36.Manifolds  tested'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name="37.Manifolds's drain lines assemblied ."),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='38.According the flow direction, pressure filter assemblied and there is enough place for changing filter element.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='39.According to flow direction return filter assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='40.Accumulator assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='41.Air filter / silika gel type air filter assemblied.'),
        ),
    ]
