# Generated by Django 3.0.8 on 2020-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0091_auto_20201218_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_3',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Are the pipelines accordance with assembly drawing and hydraulic circut?'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Are all hydraulic connections (screw connection of flanges and fittings) tight?'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Were directions changes of piping avoid? It should be preferably used round arches, angle fittings should be avoided.'),
        ),
        migrations.AlterField(
            model_name='process_3',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Are the hoses fitted professionally? (bend radious not  too small and do not contact with other parts)'),
        ),
    ]
