# Generated by Django 3.0.8 on 2020-12-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0093_auto_20201218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_6',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Return line filter installed in accordance with flow direction.'),
        ),
    ]
