# Generated by Django 3.0.8 on 2020-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0094_auto_20201218_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_6',
            name='q14',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Hose lenght controlled'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q16',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='Security ropes controlled of hoses'),
        ),
    ]
