# Generated by Django 3.0.8 on 2020-12-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0095_auto_20201218_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_7_2',
            name='q1',
            field=models.CharField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, max_length=200, verbose_name='Tested By'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q2',
            field=models.CharField(blank=True, choices=[(0, 'Aydın Kongel'), (1, 'Ferdi Akdemir')], default=0, max_length=200, verbose_name='Controlled By'),
        ),
    ]
