# Generated by Django 3.0.8 on 2020-12-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0096_auto_20201218_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_7_2',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='process_7_2',
            name='q2',
        ),
    ]
