# Generated by Django 3.0.8 on 2020-12-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0100_auto_20201223_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_2',
            name='q30',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='30.30Silica gel / air filter is OK'),
        ),
        migrations.AlterField(
            model_name='process_2',
            name='q31',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='31.Terminal box is OK'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='32.Pump-Electric Motor assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q11',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='41.Hose connections types, size and lenghts defined and ordered.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q12',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='42.Manometer panel welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='43.Protection covers are welded of oil tank for heater or switches.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q14',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='44.terminal box connection profile welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q15',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='45.Valve stand assembly done'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q16',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='46.Accumulator stand assembly done.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q17',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='47.Design department informed about all asssembly problems '),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q18',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='48.Manifold connection plates welded.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='33.Oil pan assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='34.Pump-Electric Motor group assemblied on tank'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='35.Manifolds  tested'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name="36.Manifolds's drain lines assemblied ."),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='37.According the flow direction, pressure filter assemblied and there is enough place for changing filter element.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='38.According to flow direction return filter assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='39.Accumulator assemblied.'),
        ),
        migrations.AlterField(
            model_name='process_2_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='40.Air filter / silika gel type air filter assemblied.'),
        ),
    ]
