# Generated by Django 3.0.8 on 2020-12-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0101_auto_20201224_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_2',
            name='q30',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='30.Silica gel / air filter is OK'),
        ),
    ]
