# Generated by Django 3.0.8 on 2020-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0103_auto_20201226_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_5',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='process_5',
            name='q6',
        ),
        migrations.AddField(
            model_name='process_5_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='If there is surface where is extended out of HPU and has a risk for safety the related are is painted with different color.'),
        ),
        migrations.AddField(
            model_name='process_5_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I waited the dryin period and than checked the hardness of paint.'),
        ),
        migrations.AddField(
            model_name='process_5_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='All preventive masks removed after painting'),
        ),
        migrations.AddField(
            model_name='process_5_2',
            name='q6',
            field=models.IntegerField(default=234, verbose_name='I measured the thickness of paint.'),
        ),
    ]
