# Generated by Django 3.0.8 on 2020-12-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0104_auto_20201226_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_5_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='If there is surface where is extended out of HPU and has a risk for safety the related are is painted with different color.'),
        ),
        migrations.AlterField(
            model_name='process_5_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='I waited the dryin period and than checked the hardness of paint.'),
        ),
        migrations.AlterField(
            model_name='process_5_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], verbose_name='All preventive masks removed after painting'),
        ),
    ]
