# Generated by Django 3.0.8 on 2020-12-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0107_auto_20201226_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_5',
            name='q3',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
