# Generated by Django 3.0.8 on 2020-12-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0108_process_5_q3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_6',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q21',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='process_6',
            name='q9',
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='The all manifolds assemblied on tank'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q10',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Accumulator installed'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q11',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Manometers installed.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q12',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Are all hydraulic connections done and  (pipings,screw connection of flanges and fittings) tighted.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Heater installed.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q14',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Hose lenght controlled'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q15',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Hose connection fittings types controlled'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q16',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Security ropes controlled of hoses'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q17',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='the production date of hoses controlled. ( its allowed the hose produces in last 2 years) '),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q18',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Hose pressure values compared with HPU test pressure'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q19',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='The hoses fitted professionaly. (e.g. Bend radii not too small. In case of contact with other parts scoring protector used)'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='The cooler installed.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q20',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='If there is contact with other parts, the protection against abrasion been provided.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q21',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='The hose security chains been correctly fitted? Secure chains lock were pressed.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Air filter installed.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Silica gel installed.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Thermostat installed'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Temprature/Level gauge installed'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Level Switch installed'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Pressure line filter installed in accordance with flow direction.'),
        ),
        migrations.AddField(
            model_name='process_6_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='Return line filter installed in accordance with flow direction.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q1',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I checked out the paint hardness and all painted surfaces.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q2',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='There is no unpainted surface.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q3',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='There is no orange peeling on surfaces.'),
        ),
        migrations.AlterField(
            model_name='process_6',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='The tank inside’s surface is free of contamination.'),
        ),
    ]
