# Generated by Django 3.0.8 on 2020-12-26 17:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0110_auto_20201226_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_7',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q21',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q22',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q23',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q24',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q25',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q26',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q27',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q28',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q29',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q30',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q31',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q32',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q33',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q34',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q35',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q36',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q37',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q38',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q39',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q40',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q41',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q42',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q43',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q44',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q45',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q46',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q47',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q48',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q49',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q50',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q51',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q52',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='q9',
        ),
        migrations.AddField(
            model_name='process_7',
            name='q1',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='I check out the Hydraulic circut.'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q2',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='I check out the test pressure.'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q3',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='I check out the set up values of valves accodance with Hydraulic circut.'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q4',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='I checked out the ıf there special test requirements or test plans.'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='q5',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='All electrical connections are done by electric technician.'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q10',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Return Fittings Control'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q11',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Function Test'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q12',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Dedected')], default=0, verbose_name='Oil Leakage'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, verbose_name='Missing Parts'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q14',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Oil reservoir has been checked from inside after test '),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q15',
            field=models.TextField(blank=True, default=0, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q16',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ral Code For First Coat'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q17',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ral Code For Second Coat'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q18',
            field=models.IntegerField(blank=True, default=0, verbose_name='Thickness For Prime Coat'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q19',
            field=models.IntegerField(blank=True, default=0, verbose_name='Thickness For Second Coat'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q20',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q21',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 1 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q22',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 2 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q23',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 3 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q24',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 4 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q25',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 5 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q26',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 6 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q27',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 7 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q28',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 8 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q29',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 9 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q30',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 10 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q31',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 11 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q32',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 12 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q33',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 13 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q34',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 14 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q35',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 15 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q36',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 16 : Pz'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q37',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 1 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q38',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 2 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q39',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 3 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q40',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 4 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q41',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 5 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q42',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 6 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q43',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 7 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q44',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 8 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q45',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 9 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q46',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 10 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q47',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 11 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q48',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 12 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q49',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 13 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q50',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 14 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q51',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 15 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q52',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valve 16 : Bar'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Assemb. Control'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q7',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], default=0, max_length=32, verbose_name='Elec.Mot.Return Dir.'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Hose Control'),
        ),
        migrations.AddField(
            model_name='process_7_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Fittings Control'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q6',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Oil tank is filled with oil.'),
        ),
        migrations.AlterField(
            model_name='process_7',
            name='q7',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], default=0, verbose_name='Im going to increase the pressure quit slowly when I start the pressure test.'),
        ),
    ]
