# Generated by Django 3.0.8 on 2020-12-26 17:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0111_auto_20201226_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_7_2',
            name='q10',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Return Fittings Control'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q11',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Function Test'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q12',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Dedected')], verbose_name='Oil Leakage'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q13',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], verbose_name='Missing Parts'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q14',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Oil reservoir has been checked from inside after test '),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q15',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Assemb. Control'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q7',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], max_length=32, verbose_name='Elec.Mot.Return Dir.'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Hose Control'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'DONE'), (1, 'Not Done')], verbose_name='Fittings Control'),
        ),
    ]
