# Generated by Django 3.0.8 on 2020-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0113_auto_20201226_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_7_2',
            name='q1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tested By'),
        ),
        migrations.AlterField(
            model_name='process_7_2',
            name='q2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Controlled By'),
        ),
    ]
