# Generated by Django 3.0.8 on 2020-12-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0116_auto_20201226_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_4',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='process_4',
            name='q9',
        ),
        migrations.AddField(
            model_name='process_4_2',
            name='q10',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I cleaned surfaces and applied passivation liquied for stainless materials welding process.'),
        ),
        migrations.AddField(
            model_name='process_4_2',
            name='q4',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I welded the cleaning  covers than checked the position of cleaning cover on tank.'),
        ),
        migrations.AddField(
            model_name='process_4_2',
            name='q5',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I welded the grounding element to oil tank.'),
        ),
        migrations.AddField(
            model_name='process_4_2',
            name='q6',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I applied TIG welding process for root pass of pipe. I applied the MAG welding for cover passess for pipe.'),
        ),
        migrations.AddField(
            model_name='process_4_2',
            name='q7',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I checked root after root pass of pipe welding. If there is sagging, I cleaned it with stone engine, grinder.'),
        ),
        migrations.AddField(
            model_name='process_4_2',
            name='q8',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I checked undercuts after cover pass.'),
        ),
        migrations.AddField(
            model_name='process_4_2',
            name='q9',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Not Relavant')], default=0, verbose_name='I checked start and finish point of MAG welds.'),
        ),
    ]
