# Generated by Django 3.0.8 on 2020-12-26 20:22

from django.db import migrations, models
import processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0118_auto_20201226_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_7',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=processes.models.Process7_image, verbose_name='Upload Image 1'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=processes.models.Process7_image, verbose_name='Upload Image 2'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=processes.models.Process7_image, verbose_name='Upload Image 3'),
        ),
        migrations.AddField(
            model_name='process_7',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to=processes.models.Process7_image, verbose_name='Upload Image 4'),
        ),
    ]
