# Generated by Django 3.0.8 on 2020-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0119_auto_20201226_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference_no',
            field=models.CharField(blank=True, default='R', max_length=200, verbose_name='Reference No:'),
        ),
    ]
