# Generated by Django 3.0.8 on 2020-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0122_auto_20201231_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_8',
            name='q5',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'N.OK'), (2, 'Not Applicable')], verbose_name='Hose Pressure Limit / Security Rope'),
        ),
    ]
