# Generated by Django 3.0.8 on 2020-12-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0125_auto_20201231_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
