# Generated by Django 3.0.8 on 2021-01-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0126_remove_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_7',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='process_7',
            name='picture4',
        ),
    ]
