# Generated by Django 3.0.8 on 2020-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200430_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(default='unvandeneme', max_length=20),
            preserve_default=False,
        ),
    ]
